### ISSUE TITLE
How to execute multiple test cases at the same time

### ISSUE THREAD

**Issue by abigcoder04** [QuantumPackage/qp2#213]
hello, I see many test cases in the/tests/input directory. I want to ask can I execute multiple test cases at the same time. Or these cases must be executed one by one.

**Comment by v1j4y** [comment]
Not all tests can be run in parallel. This is due to the fact that some tests depend on others to run. For e.g. the Hartree-Fock tests have to be run before doing the CIS/CISD tests as they require the molecular orbitals from the latter.

**Comment by abigcoder04** [comment]
@v1j4y For example, multiple test cases do not affect each other and only run in scf. Can this be achieved

**Comment by v1j4y** [comment]
Yes this should be possible.

**Comment by abigcoder04** [comment]
@v1j4y I tried to use the script to execute multiple examples, but the script showed no qp instruction when executing. Could you please tell me how to write a script to execute multiple examples

**Comment by scemama** [comment]
Each run runs in parallel with OpenMP, so running multiple tests at the same time will not be much faster. In addition, it will require much more memory (the sum of the memory for all the simultaneous running tests) and it will put more pressure on the file system. As the tests depend on each other, making them run in parallel needs refactoring, which we don't want to do because it will probably not be beneficial.
