### ISSUE TITLE
Issue with print_wf after running CIPSI calculation

### ISSUE THREAD

**Issue by bavramidis** [QuantumPackage/qp2#241]
Hello,

I am able to run FCI (CIPSI) calculations, and am able to print out all determinants using qp_run print_ci_vectors, but running qp_run print_wf only seems to print 10,000 determinants which I understand is the default. 

Documentation states that one can go into the determinant folder within the EZFIO and change the number of determinants that are printed with print_wf by choosing a desired # in determinants/n_det_print_wf, however I find that even if I change n_det_print_wf to, say, 100,000 , it still only prints 10,000 determinants. 

Is there way around this issue I seem to be missing? 

Thanks,
Ben

**Comment by Ydrnan** [comment]
Hello,

Can you provide us the branch and the commit you are using ?

I join a small script: [script.txt](https://github.com/QuantumPackage/qp2/files/10582500/script.txt) 
You just have to replace the .txt in .sh and change the path to source qp2. If you are not using bash you can directly past the content of the file in command line. Can you try it to see if the problem remains ?

If it does not work can you give us a tar.gz of an ezfio with a script to reproduce your problem ?

Thanks
Yann

**Comment by bavramidis** [comment]
Hello Yann,

I believe I know what my problem was now. 

Instead of setting n_det_print_wf through the main .sh file, I was setting this manually. Same with read_wf. 

If one uses the commands in the script you sent within the .sh file, changing these parameters isnt a problem. Changing manually by going into EZFIO/determinants , then running qp run print_wf doesnt seem to register the changes made within the EZFIO. 

Best to make changes within the .sh file.

Thanks!

Ben

**Comment by Ydrnan** [comment]
Hello @bavramidis, 

So, there are two different ways to change the settings.
* The first one is to write in the terminal or in a script:
`qp set_file #ezfio_name`
`qp set #module_name #parameter #value`

* The second one is to write in the terminal:
`qp set_file #ezfio_name`
`qp edit`
or 
`qp_edit #ezfio_name`
in order to edit by hand the parameters of the ezfio.

I will recommand you to set the parameters in command line for small calculations. For larger calculations, it might be better to set them in a script in order to be sure of what you have done. Finally, looking at the parameters via `qp edit` will help you to know/understand the different parameters. 

I hope it will help you to use qp2 without any problem.

Yann
