### ISSUE TITLE
QP2 Slave Jobs: f77_zmq_send Error

### ISSUE THREAD

**Issue by NastaMauger** [QuantumPackage/qp2#349]
Hello,

I am now encountering an issue with QP2 while using slave jobs. At some point, I get this error:

```
* Number of states                                             1
* Number of states in diagonalization                          4
* Number of determinants                                       169206
* Number of CSFs                                               50321
* Number of threads for diagonalization                        12
* Memory (Gb)                                                  0.08058419451117516

===== ================ ===========
Iter       Energy        Residual
===== ================ ===========
 davidson_csf_pull_results : f77_zmq_send (zmq_socket_pull,...
STOP -1
 task_done_to_taskserver: 
 davidson_slave_workUnable to send task_done

```

I am unsure where this behavior might be coming from, as running without slave jobs works perfectly fine. I have added `sleep` and `wait` commands to my script to ensure proper initialization and job completion, but the issue persists.

I have attached the different output files to this thread for reference. In case it is relevant, I installed the master using `gfortran_avx.cfg` on Linux:

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.5 LTS
Release:	22.04
Codename:	jammy

Any insights into what might be causing this or how to resolve it would be greatly appreciated.

Best regards

Script: [script.txt](https://github.com/user-attachments/files/17337209/script.txt)
Output Script: [output_script.txt](https://github.com/user-attachments/files/17337213/output_script.txt)
Master FCI output: [fci_nat_orb_0.txt](https://github.com/user-attachments/files/17337219/fci_nat_orb_0.txt)
Slave Output (only the cpu 0 is added for clarity since they are equivalent):  [fci_slave_0.txt](https://github.com/user-attachments/files/17337221/fci_slave_0.txt)

**Comment by NastaMauger** [comment]
I forgot to mention that launching my script and manually opening several terminals to start the slave jobs, instead of doing it through a script, leads to the same issue

**Comment by NastaMauger** [comment]
It turns out that using the `dev-stable` branch, my script runs perfectly fine. 

I decided to try this branch based on this thread: https://github.com/QuantumPackage/qp2/issues/306. However, that issue was resolved last year, and the last commit on `master` was just 3 weeks ago. Moreover, that commit merged changes from this specific branch: `dev-stable`.

I naively thought the issue on `master` was fixed due to that commit. 

Here are my questions:
- Is this slave behavior on `master` a known issue previously observed
- Can I use `dev-stable` for production runs of my script, or is it not considered 'safe'?

Let me know.

Best regards

**Comment by scemama** [comment]
Hello,

thank you for telling us about this problem.

First of all, I remarked in your script that you are running slaves on the same host as the master.
In theory, it should work but it will be much less efficient than running only the master process:
the slaves are intended to be run only in _multi-node_ situations.

You should run only one QP instance per node, whether a master or a slave. Each QP instance will already try to use all available cores (defined with `OMP_NUM_THREADS`). So when you are running 8 slaves, each calculation is trying to run on 8 cores, and you end up with 64 threads competing together for resources using 8x more RAM.

In this regime, the poor task server doesn't have enough resources left to work fast enough. This probably explains the error. I have already seen this kind of behavior when the network is very slow. For example when the QP_NIC network interface is not set, and the administration network is used instead of the infiniband network.

If you use 10 compute nodes (one master and 9 slaves) with >1M determinants using an 10G ethernet or infiniband network, everything will work fine.

The master branch is the safest one, and I confirm that the dev-stable branch is safe if it has the green tick on github telling that the tests pass.

best,
Anthony

**Comment by NastaMauger** [comment]
Hello,

I believe my misunderstanding arose from thinking that slave jobs were equivalent to running mpirun -np _x_ processes.

For now, I want to run my jobs on several cores rather than multiple nodes. Therefore, I have re-installed master branch QP2 using gfortran_mpi_mkl(without using Apptainer directly on my own laptop).

Currently, if I run the following command:

`mpirun -np 1 qp_run scf $mol.ezfio`

it works fine. However, when I increase the number of processes, I encounter the following error:
```
Fatal error: exception Sys_error("methane.ezfio/work/qp_run_address: No such file or directory")
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 1302258 RUNNING AT nastasia-precision-5530
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================
```

Although it returns the correct SCF energy and initializes my job with messages like:

Task server running: tcp://127.0.1.1:41319
Task server running: tcp://127.0.1.1:41349
Task server running: tcp://127.0.1.1:41329
Task server running: tcp://127.0.1.1:41339

When I try the same command with:

`mpirun -np 1 qp_run fci $ezfio > fci_nat_orb_${nat_orb}.out`

it works perfectly. However, increasing the number of processes results in the following error:

```
Abort(941695758) on node 1 (rank 1 in comm 0): Fatal error in internal_Bcast: Unknown error class, error stack:
internal_Bcast(4152)....................: MPI_Bcast(buffer=0x1862740, count=20, MPI_DOUBLE_PRECISION, 0, MPI_COMM_WORLD) failed
MPIR_Bcast(490).........................: 
MPIDI_Bcast_intra_composition_gamma(559): 
MPIDI_NM_mpi_bcast(141).................: 
MPIR_Bcast_intra_binomial(124)..........: 
(unknown)(): Unknown error class
Date: 11/10/2024 22:48:02
```

In this case, the FCI procedure completely stops. This issue occurs specifically with `-np 2`, while `-np 4` works. However, it is slower than `-np 1`

Is there a way to run multiple processes on several CPUs within a single node?

Thank you for your help!

**Comment by scemama** [comment]
> I believe my misunderstanding arose from thinking that slave jobs were equivalent to running mpirun -np _x_ processes.

For multicore, we use OpenMP parallelism. So there is no point in running multiple processes (slaves) on the same node: it is slower and uses much more memory. Don;t do it.

For inter-process parallelism, we use ZeroMQ to allow an elastic allocation of resources: after running for a few hours, if you observe that your job runs too slowly you can add slaves to accelerate it. This avoids reserving many resources when the calculations is still too small to take advantage of massive resources, so it saves CPU hours in reservations and energy.
 
As there is no efficient broadcast of data with ZeroMQ, we can start MPI slaves. The MPI slaves are always supposed to run with one MPI process per node, because the slaves are also OpenMP parallelized. The rank-0 process of the MPI slave performs all the ZeroMQ connections with the master, and then broadcasts efficiently the data to the other slaves within the MPI group of processes. So MPI is used here only to accelerate the broadcast of data, but it is not mandatory to use MPI: you can run multiple independent single process slaves.

MPI is not expected to work if you run multiple MPI processes on the same node, and running mpirun on the master process neither.

Each process always uses the maximum number of cores on the node with OpenMP. So the good behavior is
- One process per node
- All cores per process

For example, to run on 5 nodes, each node having 64 cores you should use:
```
#SBATCH -N 5 -n 5 -c 64

qp_srun fci input.ezfio
```

Only the fci program can take advantage of multiple nodes. All the rest is single-node, using OpenMP. So qp_srun should be occasional, only in for super-large runs that run too slowly on a single node.
Note: the memory is not distributed but replicated, so using multiple nodes only makes the program run faster.

So to run the scf program with multiple cores, you can't do better than `qp_run scf`.

**Comment by NastaMauger** [comment]
Thank you for taking the time to answer my question with so much detail. It really helped me understand why what I was doing didn’t make sense and gave me a better understanding of OpenMP.

Now, I am able to run on several CPUs without any issues. I’m really fast now, and I love that! :-)

Best

**Comment by scemama** [comment]
Hello,
thank you for the feedback! :-)
